### ISSUE TITLE
Selected images from gallery disappears on device screen rotation 

### ISSUE THREAD

**Issue by iamank1t** [hanjoongcho/aaf-easydiary#10]
#### Expected behavior
While writing a diary, i can select few images from my gallery to add in my diary. After selecting images if i rotate my device from portrait to landscape or landscape to portrait, the app needs to keep the selected images not to remove them from preview section.

#### Actual behavior
In write diary section, i click on select image section and select images from my device gallery. The images showing in bottom section of screen but when i rotate my screen from portrait to landscape, the images just disappears.
![Screenshot_20180306-083626.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520305897/sfe5aivdfdsva6b7f8vf.png)

#### How to reproduce
To reproduce the bug, follow the following steps :-
- Open app and click on pencil icon to write a diary.
- Click on image icon and select image from device gallery.
- After selection you see your images are at bottom of screen, now just rotate your screen and you see the images got disappear. Now you have to select images again to add in your diary.

<pre><code>
* Device:  Samsung J7 Prime
* Operating system: Android 7.0 Nougatt
* App Version: v4.16.9
</code></pre>

#### Recording Of The Bug
Note :- To understand keep eye at screen bottom.
  
 https://www.youtube.com/watch?v=qEZOK2XKwNw 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@iamankit/selected-images-from-gallery-disappears-on-device-screen-rotation">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by hanjoongcho** [comment]
Fixed bug in 330bd2c commit.
Please note that this will be applied to v1.4.27 which will be distributed later.
