### ISSUE TITLE
Strange toast message every reboot

### ISSUE THREAD

**Issue by pudup** [hanjoongcho/aaf-easydiary#101]
Everytime I reboot my phone, I have a toast message popup from easydiary saying exactly this

>"Reschedule enabled alarms that Easy Diary"

What does this mean?

**Comment by hanjoongcho** [comment]
@pudup 
The test code for Diary Write Notifications, which will be supported in the future, appears to have been released without being disabled in version 1.4.120.
Currently there is no function to set an alarm, so only the message is displayed and nothing happens.

**Comment by pudup** [comment]
Alright thanks :>
