### ISSUE TITLE
"Write date" in Excel file not correctly displayed

### ISSUE THREAD

**Issue by stikice** [hanjoongcho/aaf-easydiary#102]
When I click "Export excel", it saves excel file with diary notes and everything looks fine, except the last column Write date (Since January 1st 1970 in milliseconds.) having such values 1581058409378, 1580970960347, ...
I don't understand why this column is needed and why it is in seconds and since 1970.

![Screenshot](https://user-images.githubusercontent.com/49421659/75549599-40445d00-5a5a-11ea-9fc8-3d938d1be02d.png)

**Comment by hanjoongcho** [comment]
@stikice 
It's the difference, measured in milliseconds, between the current time and midnight, January 1, 1970 UTC(coordinated universal time).
If you have this standard time information, you can easily create time information for a specific locale.
Therefore, regardless of the device's locale setting, last column values in the Excel file are saved in UTC, and the write date column is saved in the date format that matches the device's locale.

**Comment by stikice** [comment]
Ok, thank you for a response, sorry for the inconvenience
