### ISSUE TITLE
Filter notes by symbol is remain during the use of application

### ISSUE THREAD

**Issue by stikice** [hanjoongcho/aaf-easydiary#108]
When you choose filter by symbol, for example, by cloud and sun, and then go to another screen and return back, the filter is not canceled, as should be. 
Another issue that there is no button to reset the filter, except filter by none, for example it will be good, if "X" will delete the filter together with the searched text .   
![Screenshot_2020-03-13-17-22-37-307_me blog korn123 easydiary](https://user-images.githubusercontent.com/49421659/76619988-625bd600-6556-11ea-88ea-6b35932a2b04.png)
Tested on: Xiaomi Redmi Note 4, Android 6.0

**Comment by hanjoongcho** [comment]
@stikice 
You can reset the symbol by selecting the 'none' symbol.
But I don't think it's a good way.
Let's think of a good way by referring to the opinions you gave.

**Comment by hanjoongcho** [comment]
Clicking the x button changed the symbol filter to be initialized.
