### ISSUE TITLE
in Context.kt hardcoded Korean strings

### ISSUE THREAD

**Issue by soenkegissel** [hanjoongcho/aaf-easydiary#11]
This needs to be corrected in order to display "OK" and "Cancel" in local language:
![image](https://user-images.githubusercontent.com/13346316/38675390-cec7a79c-3e57-11e8-99c5-fc7d0593efc9.png)

**Comment by soenkegissel** [comment]
Corrected version:
![image](https://user-images.githubusercontent.com/13346316/38675505-419b5430-3e58-11e8-8ca3-e6cec5eb194b.png)

**Comment by hanjoongcho** [comment]
Yes, I will fix it right away.
Thank you. =)
