### ISSUE TITLE
Can't recover data from local backup file.

### ISSUE THREAD

**Issue by username-is-not-available** [hanjoongcho/aaf-easydiary#111]
I have a backup file from 5th Jan 2020. But there is no option to choose backup file manually.
Easy Diary Version: 1.4.124
Android version: 10

**Comment by hanjoongcho** [comment]
@username-is-not-available 
In case of backup using device storage other than Google Drive, the user cannot select the location of the backup file.
You can select only backup files stored in application storage that are not accessible by the file explorer.
In the latest version, the ability to back up or select the entire data to the desired location has been added.
However, since this function is for the entire data (zip file), you cannot select individual database backup files.

**Comment by username-is-not-available** [comment]
@hanjoongcho 
So, archiving the file and using '[BETA] Backup full data' should work. I have already tried that, and a notification arrives that 'Import complete. You can now select a restore point using the Restore Diary feature'. But recover doesn't seem to have been completed because, there are only the four default posts in the home screen. I can't find the Restore Diary feature anywhere.
Attached screenshot of the notification for reference.
![photo_2020-04-10_11-16-55](https://user-images.githubusercontent.com/62513154/78967194-652ef400-7b1f-11ea-907c-a48d270dd997.jpg)

**Comment by hanjoongcho** [comment]
@username-is-not-available 
1. Click 3 dots on the top right of the main screen
2. Move to the backup menu using Device Strage
![image](https://user-images.githubusercontent.com/7098851/78995518-7c043380-7b7d-11ea-87c3-e17b60abb14e.png)

**Comment by username-is-not-available** [comment]
Sorry. I messed up in the earlier comment. When I compressed my backup file, and tried to recover it using '[BETA] Recover Full Data' I got a notification saying "Import complete. You can now select a restore point using the Restore Diary feature." I don't see 'Restore Diary' option. 
I tried clicking on 'Recover Diary' but that is not working.

**Comment by hanjoongcho** [comment]
@username-is-not-available 
The full data backup and recovery functions operate as follows.
01. [BETA] Backup full data execution
02. Export all content as a zip file
    - Attached photo
    - Post card
    - Fonts
    - Manual save diary backup file(기존에 사용자가 Device Storage Backup diary기능으로 저장한 파일들)
    - Auto save diary backup file(zip파일 압축시점에 자동으로 생성하는 백업파일/1.4.122버전 이상인 경우만 생성함)
03. [BETA] Recover full data execution
04. Import all content from zip files
    - Attached photo
    - Post card
    - Fonts
    - Manual save & Auto save diary backup file
05. Move Application Backup and Restore(Device Storage)
06. Recover Diary execution
07. Manual save & Auto save diary backup file list opend

Even if you perform backup and restore operations in the above order, do you not see the list in 07 items?

**Comment by username-is-not-available** [comment]
@hanjoongcho 
I don't want to create a backup. I already have a backup file created from an earlier version (before 5th Jan 2020). I need to recover that.
Before Jan 5, 2020 the application storage was accessible from File Manager. Since then I have changed my phone. Now, I want to recover data from that earlier backup file. I'm sorry, there has been some confusion. I've changed the title now.

**Comment by hanjoongcho** [comment]
@username-is-not-available 
In response to the 'Scoped Storage' policy of Android 10, all functions that accessed the user's storage have been removed.
I will provide the desired function by using 'SAF (Storage Access Framework)', which is currently used in the full data backup and recovery function under Beta testing.
I will let you know when the feature is developed.
Once that feature is added, you can restore the diary to the diary.realm_20200105_xxxxxx file created in the past.

**Comment by username-is-not-available** [comment]
Ah! Thank you very much! I am closing this issue now.
Thanks again, for creating this awesome app!

**Comment by hanjoongcho** [comment]
@username-is-not-available 
This feature added in version 1.4.127

**Comment by username-is-not-available** [comment]
@hanjoongcho 
This works as supposed. Thanks!
