### ISSUE TITLE
Add a nice selection of predefined TTF

### ISSUE THREAD

**Issue by soenkegissel** [hanjoongcho/aaf-easydiary#12]
Instead of just 3 pre added fonts it would be very nice to add a nice selection of more than these 3 fonts to the app.

**Comment by hanjoongcho** [comment]
@soenkegissel 
As I was organizing the issues, there were items that I could not comment on.
I'm late, but I'll reply
I do not provide various fonts to make the app lighter.
However, there is a function that allows users to add and use their own fonts.
