### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by carlostkd** [hanjoongcho/aaf-easydiary#130]
Hi i have cloned all the source code to android studio, followed the install instructions , installed on my phone but the app does not opens crash at startup, tried with many other android versions on the emulator but the app always crash, in android studio i have no errors but a lot (160) warnings.

Any advice would be welcome

Thanks in advanced

Cheers

**Comment by hanjoongcho** [comment]
Hello @carlostkd 
Can you share android studio log in app crash situation?
