### ISSUE TITLE
Hindi locale not working

### ISSUE THREAD

**Issue by Prasanta-Hembram** [hanjoongcho/aaf-easydiary#139]
I tried changing the system language in Hindi but only dates are changing. Possibly something went wrong with locale.
![Screenshot_2020-11-25-17-54-05-691_me blog korn123 easydiary](https://user-images.githubusercontent.com/51163799/100236145-49b01680-2f53-11eb-99fc-1f3349c99c9c.jpg)

**Comment by hanjoongcho** [comment]
Hi~ @Prasanta-Hembram 
Is the application version 1.4.153 correct?
My mobile phone is a Galaxy S9, and the Hindi settings are applied normally.
![image](https://user-images.githubusercontent.com/7098851/100253828-f1920800-2f84-11eb-9db2-fa1103fff66a.png)
![image](https://user-images.githubusercontent.com/7098851/100253880-0078ba80-2f85-11eb-8653-500023bf9da8.png)

**Comment by Prasanta-Hembram** [comment]
I have reinstalled the app and tested it is now working fine. I don't know after updating the app to latest version then also language was not changing with system language. After reinstalling its now good. Also a small problem may not be an issue but i detected that the examples language that were given were not changing, whenever i change system language from Hindi to English they were still in Hindi. Are you able to replicate that.
![Screenshot_2020-11-25-22-04-22-561_me blog korn123 easydiary](https://user-images.githubusercontent.com/51163799/100257812-5a20bb00-2f6c-11eb-80ce-e3dcbf2dcf3f.jpg)


Conclusion: After reinstalling the application Language selection is working fine.

**Comment by hanjoongcho** [comment]
@Prasanta-Hembram 
The sample diary creates sample data in the language set at the time of initialization and saves it in the device database.
Therefore, the sample data language does not change even if the language is changed later.
This is the same principle that the contents of the diary entered by the user are not changed by changing the language.
There are only two ways to view the initial sample data in Hindi.
After setting in Hindi, reinstall the app
Delete all saved diaries after setting in Hindi

**Comment by Prasanta-Hembram** [comment]
Thanks @hanjoongcho for nice clarification.
