### ISSUE TITLE
android.os.FileUriExposedException on Android 8 devices

### ISSUE THREAD

**Issue by soenkegissel** [hanjoongcho/aaf-easydiary#14]
To access a file in targetSdkVersion >= 24 it is not allowed anymore to just create an instance of File. It needs to use FileProvider instead.
There is an android.os.FileUriExposedException happening in PostCardActivity.shareDiary.

See explanation and implementation here:
https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

**Comment by soenkegissel** [comment]
Same problem for the TTFs. Only "device setting font" is shown.

**Comment by hanjoongcho** [comment]
A bug 'android.os.FileUriExposedException' has been fixed.
I will push it right away.
