### ISSUE TITLE
[BUG] App keep on crashing when clicked on All statistics by symbol

### ISSUE THREAD

**Issue by Prasanta-Hembram** [hanjoongcho/aaf-easydiary#145]
Steps to reproduce: Click on dairy, and click on the top right corner the application > statistics > All statistics by symbol.

Problem:When it is clicked on, all statistics by symbol then, the app either crashes or set you to your dashboard.
Device: Redmi 5 (Rosy) - Android 8.1
![Screenshot_2021-01-16-12-05-38-862_me blog korn123 easydiary](https://user-images.githubusercontent.com/51163799/104799371-a95ccc80-57f4-11eb-8f49-6c1774568884.jpg)

**Comment by hanjoongcho** [comment]
Hi~ @Prasanta-Hembram 
Reproduced the problem on some devices a few months ago and fixed the bug. Are you still experiencing this issue?

**Comment by Prasanta-Hembram** [comment]
Hello @hanjoongcho, the problem is now fixed. No more crash problem. Thanks for fixing the issue.
