### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by Poussinou** [hanjoongcho/aaf-easydiary#17]
Hi,

Since this app is Apache v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind, that do not use Google Play nor anything else, except F-Droid.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by hanjoongcho** [comment]
Thank you for your feedback.
Let's look at deploying applications using F-Droid.
If you need help, we will ask for your help =)

**Comment by IzzySoft** [comment]
@hanjoongcho 

    implementation "com.google.android.gms:play-services-drive:$versions.gms"
    implementation "com.google.android.gms:play-services-auth:$versions.gms"

are show-stoppers. Can you provide a FOSS build-flavor that comes without those? Else I'm afraid F-Droid inclusion might not be possible.

**Comment by hanjoongcho** [comment]
We added a flavor setting to make it buildable, except for the gms library.

**Comment by IzzySoft** [comment]
Thanks @hanjoongcho! Just reported that at our end, so hopefully it will be picked up soon.

**Comment by IzzySoft** [comment]
@hanjoongcho now we have a different problem: the icons used require an account to be downloaded. No chance that we can integrate that with our build process (see [here](https://gitlab.com/fdroid/rfp/issues/601#note_137212304)). Is there an alternative?

**Comment by hanjoongcho** [comment]
@IzzySoft 
Added flavor settings, including five icons to replace Flatinon weather icons. =)

**Comment by IzzySoft** [comment]
Wow, that was fast! Thanks a lot! I've reported this on our end and asked our "integrator" to give it another try.

**Comment by Rudloff** [comment]
I confirm it now builds correctly, thanks!
