### ISSUE TITLE
Restore didn't appear

### ISSUE THREAD

**Issue by rzasharifi** [hanjoongcho/aaf-easydiary#173]
Hello. I restored a backup but my diaries doesn't shown in app! and I faced with this notification and I can't figure it out. Can you help me?
Ps: I created this backup with Android 5.1.1 and restored this backup with Android 10 lineage os. Device is samsung j700f 
![IMG_20211030_192520](https://user-images.githubusercontent.com/64254187/139540335-a9f95269-6bc5-48c1-98bd-031a5329e587.jpg)

**Comment by hanjoongcho** [comment]
Hi~ @rzasharifi 
When the complete data recovery message is displayed in the notification window, you can read the previous data in the following order in the Backup and Restore settings.
Recover Diary > Restore from internal storage > Select File

**Comment by rzasharifi** [comment]
I create full backup and I think because it's "beta" it didn't work. Fortunately I created a normal backup and restored it and it works fine. Thank you for respond
