### ISSUE TITLE
Colour of post card changes to default on screen rotation

### ISSUE THREAD

**Issue by neupanedipen** [hanjoongcho/aaf-easydiary#18]
#### Expected behavior<br>
The app is supposed to retain the choosen colours for the postcards on screen rotation.<br>
#### Actual behavior<br>
But the colour of post card changes to default on screen rotation after choosing the colours.<br>
#### How to reproduce<br>
1. Install the app from playstore.<br>
2. Launch the app.<br>
3. Select any already available notes and open it.<br>
4. Now click on post card icon from top bar.<br>
5. Now click on pencil icon or fill colour icon from top bar and choose one colour for the post card and it will be implemented for your postcard.<br>
Now change the screen orientation of the app to landscape mode. The colour of post card changes to default.<br>
* App Version: 1.0<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/-6-0b8agjz8

**Comment by hanjoongcho** [comment]
This issue has been fixed in 'v1.4.40-beta'. Thank you.

**Comment by neupanedipen** [comment]
Great! Thank you!
