### ISSUE TITLE
Option to not display anything on the widget

### ISSUE THREAD

**Issue by BloodRaven0** [hanjoongcho/aaf-easydiary#192]
Currently the widget is a huge privacy breach, because the contents of the names and first few lines of the last few entries can be viewed directly, without the need for a fingerprint (if a fingerprint lock has been set).
For people that use the app for highly sensitive information, this is a big no-no.

I propose to take the approach pf banking app widgets - they need a permission from the settings inside the app in order to display any information on the widget, and that option is turned off by default. Such an option would be placed in Settings>Lock setting.

**Comment by hanjoongcho** [comment]
Request function has been added to version v1.4.268.202204040
