### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [hanjoongcho/aaf-easydiary#199]
https://monitor.f-droid.org/builds/log/me.blog.korn123.easydiary/281#site-footer

https://issuetracker.google.com/issues/184872412 This is an issue of AGP 4.1. Updating AGP to 4.2 or above should fix it. Could you please upgrade the AGP? Thanks!

**Comment by hanjoongcho** [comment]
Hello~ @linsui 
Upgraded version. If the issue is not resolved, please let me know again.

**Comment by linsui** [comment]
Thanks!
