### ISSUE TITLE
Can't backup diary.  Doesn't prompt for permissions. Pixel 5 on Android 13.

### ISSUE THREAD

**Issue by davidregal** [hanjoongcho/aaf-easydiary#200]
I really love the app and appreciate your open source efforts.  On my Pixel 5, running Android 13, clicking to backup diary via any of these options in Settings gives message "Insufficient permission for the request feature." for:
- Backup and Restore (Google Drive) > Backup diary
- Backup and Restore (Device Storage) > Backup diary 
- [BETA] Backup full data

Also get the same message for:
- Backup and Restore (Google Drive) > Recover diary 
- Backup and Restore (Device Storage) > Recover diary 

Interestingly, I can use:
- Backup and Restore (Device Storage) > Excel file creation and email sending 
- [BETA] Recover full data

Might be related but a "Permission denied" message comes up when clicking in Settings on:

- FAQs
- Privacy Policy
- Open Source Licenses

The app never prompted for storage access permission so I never denied permission to device storage or anything of the like.  The permission prompt for location worked and gladly granted that.  Google account was added fine via "Link Google Drive account".

I tried restarting phone, clearing app storage and cache.  No luck.  I feel it is something specific to Android 13 as the backup feature works on my abandoned LG V20 running Android 8.

**App version:**
v1.4.284.20210260_gmsProd_release (284)

**Kernel version:**
4.19.239
Wed, Aug 10, 2022

**Build number:**
TP1A.221005.002

App looks great and has everything I need.  Once I can backup my diary, I'll be using this app for sure!  Let me know if any testing you want me to do or additional info.

**Comment by hanjoongcho** [comment]
Hi~ @davidregal 
It will be very helpful in finding the cause of the issue by providing detailed explanations and information on the device causing the problem.
It is assumed to be an issue related to Dangerous Permission.
We will take action and provide feedback so that you can use it normally.

**Comment by davidregal** [comment]
Hi @hanjoongcho ,

Thanks for getting back to me.  Let me know what info you need in addition to what I previously supplied.  I can provide even more detail - screenshots, step-by-step or additional device info.  

Problem device is an unlocked Pixel 5 and stock Android 13 straight from Google.  I'm loving the pure Android experience.  OS kernel version and build of is above but I forgot to mention last security update was 2022-10-05 .

**Comment by hanjoongcho** [comment]
Hi @davidregal 
In Android13 (Tiramisu) version, the unnecessary logic to check the storage access permission has been removed. This version has now been distributed as a beta version on Google Play. If you are currently participating as an Easy Diary beta tester, you can update right away. If you are not a beta tester, please click the join button to participate or wait a little longer for the full version to be released.

**Comment by davidregal** [comment]
Hey @hanjoongcho ,  That's great news!  I would be glad to a beta tester but don't know to join.  I don't see a join button in the app.  I looked through all of the settings.  I thought maybe the FAQs would tell me where to go so I tried to view the FAQs within the app but that gives a "permission denied".  Also tried to find the FAQs via Google search but nothing came up.

**Comment by hanjoongcho** [comment]
@davidregal 
If you enter the Easy Diary page in Google Play, you will see a beta tester button as shown below. I'm already participating, so I see an exit button instead of a join button.
![Screenshot_20221118-131602_Google Play Store](https://user-images.githubusercontent.com/7098851/202616646-dccc51f0-e452-46c3-a7f2-f45eb306ba9a.jpg)
You can see it by moving the page in the downward direction from the Google Play Easy Diary page.

**Comment by davidregal** [comment]
Excellent @hanjoongcho .  Beta testing done.  Backup and restore via local storage and Google Drive works!  Also the in app FAQs work.  I'll be sure to sponsor as I'm very thankful for your efforts!  Keep up the good work.  This is an excellent app.  I closed the issue but feel free to reopen if you want to keep open until full version is released.
