### ISSUE TITLE
automatic change occurs in date and time for screen rotation

### ISSUE THREAD

**Issue by kr-nahid** [hanjoongcho/aaf-easydiary#22]
#### Expected behavior
it shouldn't be change time and date what i select to notes for screen rotation

#### Actual behavior
for writing diary i click on date option to 28 may and click ok for save date . but it change to 27 may  when i rotate the phone from portrait to landscape . same situation in clock sector and it change time for screen rotation . 

#### How to reproduce
* download the app and open it
* click on create note and click on date and select a date then press ok 
* rotated your device and again click on date and see it change automatic
* same situation in clock sector

> Browser/App version: Easy Diary v1.4.40
 Operating system: android 6.0

#### Recording Of The Bug
https://www.youtube.com/watch?v=Jo1MmrLaR68

**Comment by hanjoongcho** [comment]
Your registration issue has been fixed.
In v1.4.41 and later, the problem will not occur =)
