### ISSUE TITLE
Clone of your app on Google Play?

### ISSUE THREAD

**Issue by woheller69** [hanjoongcho/aaf-easydiary#226]
https://play.google.com/store/apps/details?id=com.rucksack.diary

**Comment by hanjoongcho** [comment]
@woheller69 
There is no problem at all if you comply with the GPL-3.0 license.
We will close this issue once we confirm the public source code repository for the app you attached as a link.

**Comment by woheller69** [comment]
the issue is: there is NO source code, so it does not comply

I only attached the link to Google Play

**Comment by woheller69** [comment]
he has just uploaded the code to GitLab, because I told him he is violating GPL ...

https://gitlab.com/rucksack.dev-copyshop/diary

**Comment by hanjoongcho** [comment]
@woheller69 
Currently, I don't think there is a problem because the source code has been released.
If you agree, please close the issue.
