### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [hanjoongcho/aaf-easydiary#238]
https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8706320761 The colorpicker lib disappeared from jitpack. Could you please take a look? Thanks!

**Comment by hanjoongcho** [comment]
Hello. @linsui 
I think the problem has been solved. Could you please check?
https://github.com/hanjoongcho/aaf-easydiary/commit/2a8b3aca8dda44a18233ea5e9c68eb6eb02dd070

**Comment by linsui** [comment]
F-Droid doesn't allow this maven repo. I thought we need to build this lib from source or switch to another lib.

**Comment by hanjoongcho** [comment]
@linsui 
QuadFlask:colorpicker versions up to 0.0.13 can be obtained from jitpack. I will check if it is possible to downgrade to version 0.0.15.

**Comment by linsui** [comment]
That should work for now. But maybe jitpack will remove it in the future...

**Comment by hanjoongcho** [comment]
@linsui We downgraded the version as a workaround as it was the only way to respond quickly at this point. 😂
https://github.com/hanjoongcho/aaf-easydiary/commit/6f0f3dedf01cb104e03b97b9ba021408863e0cf2
