### ISSUE TITLE
Add support for location and moods

### ISSUE THREAD

**Issue by droidkoder** [hanjoongcho/aaf-easydiary#26]
Currently the diary doesn't store the location where the entry was made automatically and it doesn't give option to enter the mood of the author.

1) Auto detect current location and add it to the diary entry - allow user to change the location if needed
2) Allow users to enter the current mood, like happy, sad, e.t.c.

**Comment by hanjoongcho** [comment]
@droidkoder 
All the requested features are provided in version 1.4.146, which is currently being provided.
