### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by hushbee** [hanjoongcho/aaf-easydiary#29]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions for users self-service. Would love to hear from you, thanks.

**Comment by hanjoongcho** [comment]
Yes. That will be fine. If you fill out the FAQ, it will be helpful to the project. :-)
Perhaps the FAQ should be written in MANUAL.md.
See below for links in the MANUAL.md file.
https://github.com/hanjoongcho/aaf-easydiary/blob/master/MANUAL.md

**Comment by hanjoongcho** [comment]
[The issue will proceed here.](https://github.com/hanjoongcho/aaf-easydiary/issues/41)
