### ISSUE TITLE
Add FAQs and Privacy Policy Statement.

### ISSUE THREAD

**Issue by HarryHeights** [hanjoongcho/aaf-easydiary#41]
Hi, I'm Harry. 

I came across your project today while surfing the internet today. 
It's an amazing project and I'm already putting it to use.
I commend the amazing work you've done so far.
I wish to contribute to your project by creating some copies. That is FAQs and Privacy Policy documents.
I couldn't help but notice that there's no FAQs on the app. Although there's a user manual on the repository, I feel it's not helpful enough. Especially since the topics discussed on it are not so much.
For the privacy policy statement, this is quite necessary for cases where data collection takes place. I don't think you collect user information when they use the software. However, I noticed that app has full network capabilities and things like that always make people skeptical. A concise privacy policy statement will put all those skepticism to rest.

Let know what you think about this.

**Comment by hanjoongcho** [comment]
Hi. Harry!

As you said, it would be helpful if you could create a FAQ and privacy policy document.
I hope you can use Markdown for this article.
There is currently no FAQ related mark down file, so please create it yourself and request PR.

Please note that the privacy policy document is written on the link below, so please let me know if you can improve it.
Easy Diary Privacy Policy:
https://github.com/AAFactory/aafactory.github.io/blob/master/policy/PRIVACY_en.md

Thank you~ 😊

**Comment by HarryHeights** [comment]
You are welcome.


I will get to work with the FAQs. For the privacy policy, I think it needs some improvements.
I will work on the FAQs first, then we can work on the privacy policy together.

**Comment by hanjoongcho** [comment]
The FAQ document you have created will be available in the Application Information category from the next release.

**Comment by HarryHeights** [comment]
That would be really great. I'd go ahead to create a standard privacy policy statement.
I wanted to ask though; Is there any means of data collection either by you or any other third party when the app is utilized?

**Comment by HarryHeights** [comment]
Btw, I have some suggestions that will boost user experience. I'll open issues for them.

**Comment by hanjoongcho** [comment]
> That would be really great. I'd go ahead to create a standard privacy policy statement.
> I wanted to ask though; Is there any means of data collection either by you or any other third party when the app is utilized?

Easy Diary does not collect user information.
If you use the Google Drive Backup feature or the Export to Excel file feature, the content you create can be shared externally, but you will need to share the file yourself.

**Comment by hanjoongcho** [comment]
> Btw, I have some suggestions that will boost user experience. I'll open issues for them.

You can also register new issues to improve the user experience.
However, because it improves the application functionality by taking advantage of the extra time, it may take a long time to implement the function. 😅

**Comment by HarryHeights** [comment]
No qualms. I'll go ahead and log the issues and also create the other documents.

**Comment by HarryHeights** [comment]
With the Privacy Policy, I guess it's safe to say I'm done. Except of course there are other kinds of written documents you need. I will create them for you.

**Comment by HarryHeights** [comment]
Hi @hanjoongcho What's good? 

I've been thinking about creating a pictorial manual of "how to use" the app. What do you think about that? 
By the way, I also wanted to find out if you are currently working on any major component of the app. I've got this great. But, I think it will take some good time to implement. It might lead to a major overhaul of the app. Lemme know what you think about this.

**Comment by hanjoongcho** [comment]
Hi @HarryHeights
Creating a pictorial manual is a very good idea.
I was thinking about it from the past, but I could not because I did not have enough time.
 
Major modifications to application functionality are currently difficult.
Because I have a business and nowadays I have hard time betting free time.😥
But I will continue to improve the function even a little bit.
Please note that the issue is divided into long-term and short-term plans.

The long-term plan is the easydiary v1.5:
https://github.com/hanjoongcho/aaf-easydiary/projects/2
 
The short-term plan is thee easydiary v1.4:
https://github.com/hanjoongcho/aaf-easydiary/projects/1

Thank you for helping us improve the features and user experience of this diary.😃

**Comment by HarryHeights** [comment]
Okay. I totally understand your situation right now though. I'll go ahead and create the pictorial manual and send a PR. I'll also suggest the ideas I have in my head. I'll open a new issue for that. If you like the ideas, you can implement them anytime you wish. You have all the time. Maybe someone could even work on them.

**Comment by HarryHeights** [comment]
Hello! Goodday @hanjoongcho Sorry I haven't been able to send a PR for the pictorial manual. I think the images in the readme documents explains everything about how to use the app though.  Maybe they just need a little explanation and stuff.

**Comment by hanjoongcho** [comment]
Okay :-)
Through the documentation such as README.md, FAQs.md, and MANUAL.md, we will gradually improve the document so that users can easily use the diary.

**Comment by HarryHeights** [comment]
Yea. Thanks.
