### ISSUE TITLE
Android Studio Build Failed

### ISSUE THREAD

**Issue by 1emirozdemir** [hanjoongcho/aaf-easydiary#42]
`ERROR: path may not be null or empty string. path='null' ERROR 
WHAT I CAN? PLEASE HELP ME!
`

**Comment by hanjoongcho** [comment]
You need to set the signingConfig in the 'local.properties' file.
Here's how.

01. Creating a signing key
https://developer.android.com/studio/publish/app-signing#generate-key

02. Setting storeFile and storePassword in local.properties file
```
## This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
#Mon Dec 31 15:07:05 KST 2018
sdk.dir=D:/android-sdk-windows
storeFile=C:/dev/android/app-signing.jks
storePassword=yourpasswod
```
