### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by 1emirozdemir** [hanjoongcho/aaf-easydiary#43]
![günlük](https://user-images.githubusercontent.com/35995145/54070602-ed82fb80-4272-11e9-8d14-665f64e37a7d.png)

Help me! Please

**Comment by hanjoongcho** [comment]
### Update the kotlin version of the 'dependencies.gradle' file.
* As-Is
```
ext.versions = [
    gradlePlugin      : '3.2.1',
    kotlin            : '1.2.51',    
]
```
* To-Be
```
ext.versions = [
    gradlePlugin      : '3.3.2',
    kotlin            : '1.3.21',
]
```

**Comment by 1emirozdemir** [comment]
Thank you so much
