### ISSUE TITLE
Ability to modify reader voice and speed and also the ability to, pause, play,  rewind or fast forward the reading process. 

### ISSUE THREAD

**Issue by HarryHeights** [hanjoongcho/aaf-easydiary#48]
I love the comfort that comes with TTS (Text-to-speech) feature. But, sometimes, I'd have loved it if the contents of the entry were read a little bit slower. I would also have loved to modify the voice texture. 
The current voice is okay though, but, it would have been a nice thing if I could modify the voice texture or rather than modifying the texture, use a different voice. Probably have a male voice or other vocal elements. 

Another thing that would make this app really cool if I could pause the reader, rewind, fast forward or play the reader back. Today, while using this feature to read an entry, I had to engage in another that had to take my attention off the reader. I had to stop the reader because I couldn't pause it, but if it was available, I would have been able to pause it and continue after I had settled the distraction. With the idea of the pause and play button, you should understand why the rewind and fast forward function is also needed.

**Comment by hanjoongcho** [comment]
I have confirmed your feedback on improving TTS functionality.
I will add it to the list of feature implementations so that I can improve it.

**Comment by HarryHeights** [comment]
Great. Thanks
