### ISSUE TITLE
Import from other journal apps

### ISSUE THREAD

**Issue by pudup** [hanjoongcho/aaf-easydiary#69]
Is it possible to add a feature to import from other journal backups, say excel, plaintext or .json backups?

**Comment by hanjoongcho** [comment]
Technically possible. However, it has a lower priority than other features planned, and does not take into account the ability to import other application data.

**Comment by gilcu3** [comment]
while this function is implemented, is there any manual way to do this? Any way to manually generate a backup file in the currently accepted format of the app (is it documented somewhere)?

**Comment by hanjoongcho** [comment]
@gilcu3 
Unfortunately, there is currently no way.
Only the data exported from Easy Diary can be re-imported.

**Comment by gilcu3** [comment]
Is it possible to handcraft the data as if it were exported from Easy Diary?

**Comment by hanjoongcho** [comment]
@gilcu3 
By default, database files used for backup and recovery are not manually editable.
Although it provides the function to export in xlsx format, there is currently no function to import using xlsx files.
If you need to import after manual editing, the function to import xlsx files must be implemented.

**Comment by gilcu3** [comment]
I understand that within the app is impossible. But maybe if the database is a sqlite database (or some other open format), I can fill it with another program and then import it to the app as it were a normal backup. Thanks for your support

**Comment by hanjoongcho** [comment]
@gilcu3 
Easy Diary uses realm database.
Looking at the comment and looking it up, I think it is possible to do this in realm-studio.
https://realm.io/products/realm-studio/#download-studio

**Comment by gilcu3** [comment]
@hanjoongcho I managed to do it, thank you for your help. 
For reference, I made an export in the app, opened the database using Realm Studio, converted my personal data into a csv with a required format, then imported it into Realm Studio and finally restored the database using Easy Diary.
