### ISSUE TITLE
Pictures broken after entry saved.

### ISSUE THREAD

**Issue by soenkegissel** [hanjoongcho/aaf-easydiary#7]
I called one example entry. When adding a picture to it, it's shown without problem. After saving the photo is gone, just a ? 
Downloaded newest version (1.4.23).

![screenshot_20180227-151013](https://user-images.githubusercontent.com/13346316/36734176-005d842c-1bd3-11e8-945b-4112ec93a78e.png)
![screenshot_20180227-151007](https://user-images.githubusercontent.com/13346316/36734177-0079916c-1bd3-11e8-9985-b321eace4fe8.png)
![screenshot_20180227-150956](https://user-images.githubusercontent.com/13346316/36734179-0095e006-1bd3-11e8-9b6f-fd7763891770.png)

**Comment by hanjoongcho** [comment]
Have you registered using the Google Photos app?

**Comment by soenkegissel** [comment]
Yes

Bulbasaur <notifications@github.com> schrieb am Mi., 28. Feb. 2018, 01:13:

**Comment by hanjoongcho** [comment]
Unfortunately, Easy Diary does not yet support the 'Google Photos app'.
Until the photo link feature using the 'Google Photos app' is implemented, please use the 'Gallery app' to add a photo link.

Unfortunately, the Easy Diary is designed to store only the uri link without saving the original photo separately when attaching the photo, but the 'Google Photos app' does provide access to the uri link only once. 
For more information, please visit the link below:
https://stackoverflow.com/questions/30572261/using-data-from-context-providers-or-requesting-google-photos-read-permission

**Comment by soenkegissel** [comment]
Understood. No problem. I was just wondering.
Thank you very much.

**Comment by hanjoongcho** [comment]
This issue has been fixed in v1.4.25

**Comment by soenkegissel** [comment]
Your the best.
 Thank you very much!
