### ISSUE TITLE
Reference to the iconpack for gmsp flavor

### ISSUE THREAD

**Issue by soenkegissel** [hanjoongcho/aaf-easydiary#73]
I would love to use the tons of icons from the gmsp flavor, but no description is attached.
Where to find them?

<string-array name="emotion_item_array">
        <item>139|Sad</item>
        <item>128|Cry</item>
        <item>129|Happy</item>
        <item>130|Love</item>
        <item>131|Happy</item>
        <item>132|Sleep</item>
        <item>133|Smile</item>
        <item>134|Suffer</item>

**Comment by hanjoongcho** [comment]
@soenkegissel You can download it from the link below.
https://www.flaticon.com/packs/linear-color-emoticons

Complete iconpack information for the gmsp flavor build can be found in the sheet below.
https://docs.google.com/spreadsheets/d/1KRrGgT9wyemefLg0Wh9EGMtxO9ob5HEKod4uFv248Lg/edit?usp=sharing

**Comment by soenkegissel** [comment]
Can you please share a zip file with icons identical to the names from the
app. I will not rename 100 icons on my own.

Am Mo., 23. Sept. 2019 um 14:52 Uhr schrieb Bulbasaur <
notifications@github.com>:

**Comment by hanjoongcho** [comment]
@soenkegissel 
Unfortunately, I do not have permission to provide an icon for flatticon.
Check out the flatticon licensing policy below.
https://profile.flaticon.com/license/free
