### ISSUE TITLE
Copycat on Google Play

### ISSUE THREAD

**Issue by Poussinou** [hanjoongcho/aaf-easydiary#77]
Hi @hanjoongcho 

I found this app: https://play.google.com/store/apps/details?id=com.kotunsoft.easydiary on the Google Play Store. This guy just took your source code, made it paid and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under Apache v2 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by hanjoongcho** [comment]
Hi  @Poussinou 
Thank you for helping me distribute Easy Diary to F-Droid last time.

I've checked your information.
As you mentioned, the aaf-easydiary application must specify a copy of the license for an aaf-easydiary license created under the Apache v2 license.
I also believe that there should be a statement about the third party license and what parts of the fix have been changed.
If anybody can't see this in the application menu, I think the license violation is obvious.
However, I'm hesitant to pay for and verify the developer's application to see that. :(
Let me think a little more.

**Comment by Poussinou** [comment]
I don't think you should pay for this... There is no link in the description, no statement that it is FLOSS...

**Comment by hanjoongcho** [comment]
@Poussinou 
A few minutes ago, I completed a report of alleged copyright infringement.
There was no detail infringement on the reporting form.
So I've only written some of your guide.
I'll share it when the progress comes out.

**Comment by hanjoongcho** [comment]
@Poussinou 
The following is a summary of the reply.
At this time, Google has decided not to take any action. Please resolve any disputes directly with the party who posted the content.
