### ISSUE TITLE
DiaryDto.getWeather() on a null object reference

### ISSUE THREAD

**Issue by soenkegissel** [hanjoongcho/aaf-easydiary#8]
I think the screenshot explains best:
![unbenannt-1](https://user-images.githubusercontent.com/13346316/36970295-5ecfba86-2068-11e8-860d-19c3fca28dfb.png)

**Comment by hanjoongcho** [comment]
Under what circumstances does this bug occur?

Check if the mSequence value is set correctly.
In the code below, diaryDto should not be a null value.
-----   DiaryUpdateActivity.kt ----------------------------------------------------------
fun initData() {
        val intent = intent
        mSequence = intent.getIntExtra(Constants.DIARY_SEQUENCE, 0)
        val **diaryDto** = EasyDiaryDbHelper.readDiaryBy(mSequence)
        mWeather = diaryDto.weather
------------------------------------------------------------------------------------------
