### ISSUE TITLE
Media within the text

### ISSUE THREAD

**Issue by subpub** [hanjoongcho/aaf-easydiary#82]
Currently media is in a separate _attachment_, but if we can insert a image in the middle of the text pretty much like a web article it will be more nice/readable.  

 Additionally a bigger feature image (possible ,the 1st image in a entry) can be displayed in the main listview.  

- [ ] Insert media in the middle of text
- [ ] display bigger feature image in main view

**Comment by hanjoongcho** [comment]
@subpub I will review the technology to make it available when the major version is updated.
However, it is difficult to apply to the major version currently released.
