### ISSUE TITLE
Turning this into a "Snap Diet"

### ISSUE THREAD

**Issue by DonaldTsang** [hanjoongcho/aaf-easydiary#85]
Dear Joong Cho:

I would like to use this app as a Photo Food Journal as a way of helping with my "snap diet", is it possible to add Camera functionality so that I can take photos of all my meals?
(bonus if it can compress the photo to save some space while keeping it recognizable?)

Some references:
https://www.self.com/story/snap-it-photo-food-journal-for-weight-loss (introduction)
https://blog.getbitesnap.com/653887959cbf (example closed source application)

Regards, D

**Comment by hanjoongcho** [comment]
Same issue #32

**Comment by DonaldTsang** [comment]
Would like to use this issue as a reference for #32 if that is possible.
