### ISSUE TITLE
Turning this into a Bullet Journal

### ISSUE THREAD

**Issue by DonaldTsang** [hanjoongcho/aaf-easydiary#87]
It has been said that Bullet Journals are the latest fad in productivity.
Is it possible to take a look at this and see what can be made into an app?
http://libgen.is/book/index.php?md5=E9E70877EAA2AE33DE6E48F594EC26AB

**Comment by hanjoongcho** [comment]
This feature implemented in version 1.4.112

**Comment by hanjoongcho** [comment]
@DonaldTsang I will add this to my long-term plan list.

**Comment by DonaldTsang** [comment]
This one might need some clarification, but it is actually really useful once implemented. Might take some time to plan it out.

**Comment by DonaldTsang** [comment]
Here is an alternative called "Clear Journaling" which might be an alternative template.
http://libgen.is/book/index.php?md5=96F997237D1FFFE83467F130C350F275
